_target_: model.lt_ct.CompressiveTransformerEmqaModel
pretrained_enc_dec: t5-base
input_dim: ${dataset.feature_dim}
hidden_dim: 768
num_layers: 6
heads: 8
block_length: 64
mem_length: 64
cmem_lengths: [ 16, 8, 4 ]
compression_factors: [ 4, 2, 2 ]
use_ltmem: True
memory_layers: [ 1, 4, 5, 6 ]
dropout: 0.1
